"use client";

import { useState } from "react";
import { CheckIcon, DownloadIcon, PackageIcon, PrinterIcon, RotateCcwIcon } from "lucide-react";
import { toast } from "sonner";
import { createDefaultLabelData, industryPresets, labelDataSchema, labelTemplates, type LabelData, type TemplateId } from "@/lib/shipping-label";
import { cn } from "@/lib/utils/cn";

type Done = { id: string; pdfUrl: string; quantity: number };
type Errors = Record<string, string>;
const control = "mt-1.5 min-h-11 w-full rounded-lg border border-border bg-background px-3 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/20";
const options = {
  packageType: ["BOX","ENVELOPE","TUBE","PALLET","CRATE","INSULATED_BOX","POLY_BAG"],
  weightUnit: ["LB","OZ","KG","G"], dimensionUnit: ["IN","CM","MM"],
  carrier: ["USPS","UPS","FEDEX","DHL","GENERIC"], marketplace: ["SHOPIFY","AMAZON","WALMART","OTHER"],
  preset: ["ECOMMERCE","RETAIL","WHOLESALE","MANUFACTURING","FOOD_BEVERAGE","SHIPPING_TRANSPORTATION"],
  service: ["STANDARD","EXPRESS","OVERNIGHT","ECONOMY","PRIORITY","CUSTOM"],
} as const;

function Field({ label, error, children, required }: { label: string; error?: string; children: React.ReactNode; required?: boolean }) {
  return <label className="block text-sm font-semibold">{label}{required && <span className="ml-1 text-destructive">*</span>}{children}{error && <span className="mt-1 block text-xs font-normal text-destructive">{error}</span>}</label>;
}

function Preview({ data, templateId }: { data: LabelData; templateId: TemplateId }) {
  const template = labelTemplates.find((t) => t.id === templateId)!;
  const tracking = data.tracking.trackingNumber || "CUSTOM-LABEL-PREVIEW";
  return <div className={cn("mx-auto flex w-full max-w-[350px] flex-col overflow-hidden border-2 border-slate-950 bg-white text-slate-950 shadow-xl", template.width === 3 ? "aspect-[3/4]" : "aspect-[2/3]")}>
    {data.heading.showHeading && <div className="border-b-2 border-black px-4 py-3 text-center text-sm font-black tracking-wider">{data.heading.customHeading || `${data.shipping.carrier} ${data.format.serviceLevel} SHIPPING`}</div>}
    <div className="border-b border-black px-4 py-3 text-[11px] leading-relaxed"><p className="text-[9px] font-bold tracking-widest text-slate-500">FROM</p><b>{data.sender.name || "Sender name"}</b>{data.sender.company && <p>{data.sender.company}</p>}<p>{data.sender.addressLine1 || "Sender address"}</p>{data.sender.addressLine2 && <p>{data.sender.addressLine2}</p>}<p>{data.sender.city || "City"}, {data.sender.state || "State"} {data.sender.zipCode || "ZIP"}</p></div>
    <div className="flex-1 px-4 py-4 text-sm leading-relaxed"><p className="mb-2 text-[10px] font-black tracking-[.2em]">SHIP TO</p><p className={cn("font-black", template.layout === "minimal" ? "text-xl" : "text-lg")}>{data.recipient.name || "Recipient name"}</p>{data.recipient.company && <p>{data.recipient.company}</p>}<p>{data.recipient.addressLine1 || "Recipient address"}</p>{data.recipient.addressLine2 && <p>{data.recipient.addressLine2}</p>}<p className="font-bold">{data.recipient.city || "City"}, {data.recipient.state || "State"} {data.recipient.zipCode || "ZIP"}</p><b>{data.recipient.country}</b></div>
    <div className={cn("border-y-2 border-black px-4 py-3", template.layout === "barcode" && "py-5")}><div className="h-12 bg-[repeating-linear-gradient(90deg,#000_0,#000_2px,transparent_2px,transparent_4px,#000_4px,#000_5px,transparent_5px,transparent_8px)]"/><p className="mt-1 truncate text-center font-mono text-[10px] font-bold">{tracking}</p></div>
    <div className="grid grid-cols-2 gap-2 px-4 py-3 text-[9px] font-bold"><span>{data.package.type} · {data.package.weight} {data.package.weightUnit}</span><span className="text-right">{data.format.quantity > 1 ? `PACKAGE 1 OF ${data.format.quantity}` : data.shipping.marketplace}</span><span>REF {data.tracking.referenceNumber || "—"}</span><span className="text-right">{data.format.shipDate}</span></div>
    <div className="bg-slate-950 px-3 py-1.5 text-center text-[8px] font-bold tracking-wider text-white">CUSTOM LABEL · POSTAGE NOT INCLUDED</div>
  </div>;
}

export function ShippingLabelMaker() {
  const [templateId, setTemplateId] = useState<TemplateId>(1);
  const [data, setData] = useState<LabelData>(() => createDefaultLabelData());
  const [errors, setErrors] = useState<Errors>({});
  const [busy, setBusy] = useState(false);
  const [done, setDone] = useState<Done | null>(null);
  const update = <S extends keyof LabelData, K extends keyof LabelData[S]>(section: S, key: K, value: LabelData[S][K]) => { setData(v => ({...v,[section]:{...v[section], [key]:value}})); setDone(null); setErrors(v=>{const n={...v};delete n[`${String(section)}.${String(key)}`];return n;}); };
  const preset = (value: LabelData["shipping"]["industryPreset"]) => { const p=industryPresets[value]; setData(v=>({...v,shipping:{...v.shipping,industryPreset:value},package:{...v.package,type:p.packageType},tracking:{...v.tracking,handlingInstructions:p.handling}})); setDone(null); };
  const generate = async () => { const valid=labelDataSchema.safeParse(data); if(!valid.success){const e:Errors={};valid.error.issues.forEach(i=>e[i.path.join(".")]??=i.message);setErrors(e);toast.error("Please correct the highlighted fields.");return;} setBusy(true);try{const response=await fetch("/api/shipping-labels",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({templateId,labelData:valid.data})});const result=await response.json();if(!response.ok)throw new Error(result.message);setDone(result);toast.success("Your label is ready.");}catch(e){toast.error(e instanceof Error?e.message:"Label generation failed");}finally{setBusy(false);} };
  const reset=()=>{setData(createDefaultLabelData());setErrors({});setDone(null);setTemplateId(1);};

  return <div className="space-y-10">
    <section><p className="text-sm font-bold text-primary">Step 1</p><h2 className="mt-1 font-display text-2xl font-extrabold">Choose a shipping label template</h2><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{labelTemplates.map(t=><button key={t.id} type="button" onClick={()=>{setTemplateId(t.id);setDone(null);}} className={cn("relative min-h-28 rounded-xl border p-4 text-left",templateId===t.id?"border-primary bg-accent ring-2 ring-primary/20":"border-border bg-card hover:border-primary/50")}>{templateId===t.id&&<CheckIcon className="absolute right-3 top-3 h-4 w-4 text-primary"/>}<b className="block">{t.name}</b><span className="mt-2 block text-xs leading-5 text-muted-foreground">{t.description}</span><span className="mt-2 block text-[11px] font-semibold text-primary">{t.width} × {t.height} in</span></button>)}</div></section>
    <div className="grid items-start gap-8 xl:grid-cols-[1.15fr_.85fr]">
      <div className="space-y-6"><div><p className="text-sm font-bold text-primary">Step 2</p><h2 className="mt-1 font-display text-2xl font-extrabold">Enter shipping details</h2><p className="mt-2 text-sm text-muted-foreground">The preview updates instantly. Data is saved only when you generate.</p></div>
        <Address title="Sender" section="sender" data={data} errors={errors} update={update}/><Address title="Recipient" section="recipient" data={data} errors={errors} update={update}/>
        <Box title="Package"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Select label="Package type" value={data.package.type} values={options.packageType} onChange={v=>update("package","type",v as LabelData["package"]["type"])}/><NumberField label="Weight" value={data.package.weight} error={errors["package.weight"]} onChange={v=>update("package","weight",v)}/><Select label="Weight unit" value={data.package.weightUnit} values={options.weightUnit} onChange={v=>update("package","weightUnit",v as LabelData["package"]["weightUnit"])}/><Select label="Dimension unit" value={data.package.dimensionUnit} values={options.dimensionUnit} onChange={v=>update("package","dimensionUnit",v as LabelData["package"]["dimensionUnit"])}/>{(["length","width","height"] as const).map(k=><NumberField key={k} label={k[0].toUpperCase()+k.slice(1)} value={data.package[k]} error={errors[`package.${k}`]} onChange={v=>update("package",k,v)}/>)}</div></Box>
        <Box title="Shipping & format"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Select label="Industry preset" value={data.shipping.industryPreset} values={options.preset} onChange={v=>preset(v as LabelData["shipping"]["industryPreset"])}/><Select label="Carrier" value={data.shipping.carrier} values={options.carrier} onChange={v=>update("shipping","carrier",v as LabelData["shipping"]["carrier"])}/><Select label="Marketplace" value={data.shipping.marketplace} values={options.marketplace} onChange={v=>update("shipping","marketplace",v as LabelData["shipping"]["marketplace"])}/><Select label="Service" value={data.format.serviceLevel} values={options.service} onChange={v=>update("format","serviceLevel",v as LabelData["format"]["serviceLevel"])}/><Field label="Ship date" required error={errors["format.shipDate"]}><input className={control} type="date" value={data.format.shipDate} onChange={e=>update("format","shipDate",e.target.value)}/></Field><NumberField label="Packages / copies" value={data.format.quantity} error={errors["format.quantity"]} min={1} max={100} step={1} onChange={v=>update("format","quantity",v)}/></div></Box>
        <Box title="Tracking & heading"><div className="grid gap-4 sm:grid-cols-2"><TextField label="Tracking number" value={data.tracking.trackingNumber} onChange={v=>update("tracking","trackingNumber",v)}/><TextField label="Reference number" value={data.tracking.referenceNumber} onChange={v=>update("tracking","referenceNumber",v)}/><TextField label="Custom heading" value={data.heading.customHeading} disabled={!data.heading.showHeading} onChange={v=>update("heading","customHeading",v)}/><TextField label="Handling instructions" value={data.tracking.handlingInstructions} onChange={v=>update("tracking","handlingInstructions",v)}/><label className="flex min-h-11 items-center gap-3 text-sm font-semibold"><input type="checkbox" checked={data.heading.showHeading} onChange={e=>update("heading","showHeading",e.target.checked)} className="h-4 w-4 accent-primary"/>Show heading</label></div></Box>
      </div>
      <aside className="xl:sticky xl:top-24"><div className="rounded-2xl border border-border bg-muted/40 p-4 sm:p-6"><p className="mb-4 text-sm font-bold text-primary">Live preview</p><Preview data={data} templateId={templateId}/></div><div className="mt-5 rounded-xl border border-border bg-card p-5"><button type="button" onClick={generate} disabled={busy} className="inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-lg bg-primary px-5 font-bold text-primary-foreground disabled:opacity-60"><PackageIcon className="h-5 w-5"/>{busy?"Generating…":"Generate label"}</button><p className="mt-3 text-xs leading-5 text-muted-foreground">Custom printable label only. Postage and official carrier tracking are not included.</p>{done&&<div className="mt-5 border-t border-border pt-5"><p className="mb-4 flex items-center gap-2 text-sm font-semibold text-primary"><CheckIcon className="h-4 w-4"/>Label #{done.id} is ready</p><div className="grid gap-2 sm:grid-cols-3 xl:grid-cols-1 2xl:grid-cols-3"><a href={done.pdfUrl} target="_blank" className="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg bg-primary px-3 text-sm font-bold text-primary-foreground"><DownloadIcon className="h-4 w-4"/>PDF</a><button onClick={()=>window.open(done.pdfUrl,"_blank","noopener,noreferrer")} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg border px-3 text-sm font-bold"><PrinterIcon className="h-4 w-4"/>Print</button><button onClick={reset} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg border px-3 text-sm font-bold"><RotateCcwIcon className="h-4 w-4"/>New</button></div></div>}</div></aside>
    </div>
  </div>;
}

function Box({title,children}:{title:string;children:React.ReactNode}){return <fieldset className="rounded-xl border border-border bg-card p-5"><legend className="px-2 font-display text-lg font-bold">{title}</legend>{children}</fieldset>}
function Select({label,value,values,onChange}:{label:string;value:string;values:readonly string[];onChange:(v:string)=>void}){return <Field label={label}><select className={control} value={value} onChange={e=>onChange(e.target.value)}>{values.map(v=><option key={v} value={v}>{v.replaceAll("_"," ")}</option>)}</select></Field>}
function TextField({label,value,onChange,error,disabled}:{label:string;value:string;onChange:(v:string)=>void;error?:string;disabled?:boolean}){return <Field label={label} error={error}><input className={control} disabled={disabled} value={value} onChange={e=>onChange(e.target.value)}/></Field>}
function NumberField({label,value,onChange,error,min=.01,max,step=.01}:{label:string;value:number;onChange:(v:number)=>void;error?:string;min?:number;max?:number;step?:number}){return <Field label={label} required error={error}><input className={control} type="number" value={value} min={min} max={max} step={step} onChange={e=>onChange(Number(e.target.value))}/></Field>}
function Address({title,section,data,errors,update}:{title:string;section:"sender"|"recipient";data:LabelData;errors:Errors;update:<S extends keyof LabelData,K extends keyof LabelData[S]>(s:S,k:K,v:LabelData[S][K])=>void}){const a=data[section];return <Box title={title}><div className="grid gap-4 sm:grid-cols-2"><TextField label="Full name *" value={a.name} error={errors[`${section}.name`]} onChange={v=>update(section,"name",v)}/><TextField label="Company" value={a.company} onChange={v=>update(section,"company",v)}/><div className="sm:col-span-2"><TextField label="Address line 1 *" value={a.addressLine1} error={errors[`${section}.addressLine1`]} onChange={v=>update(section,"addressLine1",v)}/></div><div className="sm:col-span-2"><TextField label="Address line 2" value={a.addressLine2} onChange={v=>update(section,"addressLine2",v)}/></div><TextField label="City *" value={a.city} error={errors[`${section}.city`]} onChange={v=>update(section,"city",v)}/><TextField label="State / province *" value={a.state} error={errors[`${section}.state`]} onChange={v=>update(section,"state",v)}/><TextField label="ZIP / postal code *" value={a.zipCode} error={errors[`${section}.zipCode`]} onChange={v=>update(section,"zipCode",v)}/><TextField label="Country code *" value={a.country} error={errors[`${section}.country`]} onChange={v=>update(section,"country",v.toUpperCase().slice(0,2))}/><TextField label="Phone" value={a.phone} onChange={v=>update(section,"phone",v)}/></div></Box>}
