"use client";
import { useEffect,useMemo,useRef,useState,type ReactNode } from "react";
import { labelTemplates,type LabelData,type TemplateId } from "@/lib/shipping-label";
import { cn } from "@/lib/utils/cn";

export function LabelPreview({data,templateId,className,bordered=true}:{data:LabelData;templateId:TemplateId;className?:string;bordered?:boolean}){
 const template=labelTemplates.find(t=>t.id===templateId)!;const W=384,H=576;const ref=useRef<HTMLDivElement>(null);const [scale,setScale]=useState(.5);
 useEffect(()=>{const el=ref.current;if(!el)return;const update=()=>setScale(el.clientWidth/W);update();const ro=new ResizeObserver(update);ro.observe(el);return()=>ro.disconnect()},[]);
 return <div ref={ref} className={cn("relative w-full overflow-hidden bg-white",bordered&&"rounded-sm shadow-[0_8px_30px_-8px_rgba(0,0,0,.35)] ring-1 ring-black/10",className)} style={{aspectRatio:`${template.width}/${template.height}`}}><div className="origin-top-left bg-white text-black" style={{width:W,height:H,transform:`scale(${scale})`,fontFamily:"Arial,Helvetica,sans-serif"}}>{templateId===1&&<Marketplace d={data}/>} {templateId===2&&<MinimalMono d={data}/>} {templateId===3&&<CleanHierarchy d={data}/>} {templateId===4&&<SimpleList d={data}/>} {templateId===5&&<StandardBarcode d={data}/>}</div></div>
}
function fields(d:LabelData){return{tracking:d.tracking.trackingNumber||"9400 1118 9922 3456 7890 12",reference:d.tracking.referenceNumber||"ORD-48213",weight:`${d.package.weight} ${d.package.weightUnit}`,dims:`${d.package.length}×${d.package.width}×${d.package.height} ${d.package.dimensionUnit}`,copy:d.format.quantity>1?`1 of ${d.format.quantity}`:"1 of 1"}}
function Barcode({value,className}:{value:string;className?:string}){const bars=useMemo(()=>{let seed=2166136261,x=0;for(const c of value)seed=Math.imul(seed^c.charCodeAt(0),16777619)>>>0;return Array.from({length:80},(_,i)=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;const w=1+(seed%3),item={x,w,on:i%2===0};x+=w;return item})},[value]);const last=bars[bars.length-1];return <svg viewBox={`0 0 ${last.x+last.w} 10`} preserveAspectRatio="none" className={className} aria-hidden>{bars.filter(b=>b.on).map((b,i)=><rect key={i} x={b.x} width={b.w} height="10"/>)}</svg>}
function Address({a,large=false}:{a:LabelData["sender"];large?:boolean}){return <div className={large?"text-[18px] leading-[1.22]":"text-[11px] leading-[1.35]"}><div className={large?"text-[25px] font-black":"font-bold"}>{a.name||"Daniel Okafor"}</div>{a.company&&<div className={large?"text-[19px]":""}>{a.company}</div>}<div>{a.addressLine1||"88 Maple Row, Apt 12B"}</div>{a.addressLine2&&<div>{a.addressLine2}</div>}<div>{a.city||"Austin"}, {a.state||"TX"} {a.zipCode||"78704"}</div><div>{a.country||"US"}</div>{a.phone&&<div className="mt-1">{a.phone}</div>}</div>}
const date=(s:string)=>{const d=new Date(s);return Number.isNaN(d.getTime())?s:d.toISOString().slice(0,10)};
const Pill=({children,fill=false}:{children:ReactNode;fill?:boolean})=><span className={cn("rounded-md border-2 border-[#147f77] px-2 py-1 text-[11px] font-black",fill&&"bg-[#147f77] text-white")}>{children}</span>;

function Marketplace({d}:{d:LabelData}){const f=fields(d);return <div className="flex h-full flex-col p-[14px] text-[#07110f]"><div className="flex items-center justify-between"><span className="rounded-full bg-[#147f77] px-3 py-1 text-[12px] font-black tracking-wide text-white">{d.shipping.marketplace} ORDER</span><b className="font-mono text-[13px]">#{f.reference}</b></div><div className="mt-3 flex-1 rounded-[15px] border-2 border-[#147f77] bg-[#eaf7f5] p-3"><div className="text-[11px] font-black tracking-wider text-[#147f77]">DELIVER TO</div><Address a={d.recipient} large/></div><div className="mt-3 flex flex-wrap gap-1.5"><Pill>{d.package.type}</Pill><Pill>{f.weight}</Pill><Pill>{f.dims}</Pill><Pill fill>{d.format.serviceLevel}</Pill></div><div className="mt-3 text-[10px]"><b>Return to:</b> {d.sender.name||"Sender"}, {d.sender.addressLine1||"Return address"}, {d.sender.city||"City"}, {d.sender.state} {d.sender.zipCode}</div><Barcode value={f.tracking} className="mt-3 h-[64px] w-full"/><div className="mt-1 text-center font-mono text-[11px] font-bold">{f.tracking}</div><div className="mt-3 rounded-md bg-[#147f77] py-1.5 text-center text-[14px] font-black text-white">Thank you for your order</div></div>}
function MinimalMono({d}:{d:LabelData}){const f=fields(d);return <div className="h-full p-[14px] font-mono text-[11px] font-semibold"><div className="flex justify-between border-b-[3px] border-black pb-1 font-bold"><span>SHIPPING LABEL</span><span>{f.copy}</span></div><div className="border-b border-black py-2"><b>FROM </b>{d.sender.name||"Sender"} / {d.sender.company}<br/>{d.sender.addressLine1||"Return address"}<br/>{d.sender.city}, {d.sender.state} {d.sender.zipCode}</div><div className="pt-2"><b>TO</b><Address a={d.recipient}/></div><div className="my-2 border-y border-black py-1 text-[58px] font-black leading-none">{d.recipient.zipCode||"78704"}</div><div className="grid grid-cols-2 border-b border-black">{[["PKG",d.package.type],["WT",f.weight],["DIM",f.dims],["SVC",`${d.shipping.carrier} ${d.format.serviceLevel}`],["DATE",date(d.format.shipDate)],["REF",f.reference]].map(([k,v])=><div key={k} className="border-b border-r border-black p-1"><b>{k}</b> {v}</div>)}</div><div className="border-b border-black py-2"><b>NOTE </b>{d.tracking.handlingInstructions||"Handle with care"}</div><Barcode value={f.tracking} className="mt-3 h-[72px] w-full"/><div className="text-center text-[11px] font-bold">{f.tracking}</div></div>}
function CleanHierarchy({d}:{d:LabelData}){const f=fields(d);return <div className="flex h-full flex-col p-5"><div className="text-[10px] font-black tracking-[4px]">PRIORITY SHIPMENT</div><div className="mt-4 grid grid-cols-[1fr_auto] text-[11px]"><div><b>FROM</b><Address a={d.sender}/></div><div className="text-right"><b>SHIP DATE</b><br/>{date(d.format.shipDate)}<br/><b>WEIGHT</b><br/>{f.weight}</div></div><div className="mt-8"><div className="text-[10px] font-black tracking-[3px]">SHIP TO</div><Address a={d.recipient} large/></div><div className="mt-auto border-t-2 border-black pt-2 text-[12px] font-black">{d.shipping.carrier} {d.format.serviceLevel} · {d.package.type} · {f.dims} · {f.copy}</div><Barcode value={f.tracking} className="mt-3 h-[70px] w-full"/><div className="mt-2 flex justify-between font-mono text-[10px]"><span>{f.tracking}</span><span>{f.reference}</span></div></div>}
function SimpleList({d}:{d:LabelData}){const f=fields(d),rows=[["PACKAGE",`${d.package.type}, ${f.weight}, ${f.dims}`],["SERVICE",`${d.shipping.carrier} ${d.format.serviceLevel}`],["MARKETPLACE",d.shipping.marketplace],["SHIP DATE",date(d.format.shipDate)],["REFERENCE",f.reference],["HANDLING",d.tracking.handlingInstructions||"Handle with care"],["COPY",f.copy]];return <div className="flex h-full flex-col p-5"><div className="grid grid-cols-[84px_1fr]"><b className="text-[10px] tracking-wider">SHIP TO</b><Address a={d.recipient} large/><b className="mt-4 text-[10px] tracking-wider">FROM</b><div className="mt-4"><Address a={d.sender}/></div></div><div className="mt-4 border-t-2 border-neutral-500 pt-3">{rows.map(([k,v])=><div key={k} className="grid grid-cols-[94px_1fr] py-1.5"><b className="text-[10px] tracking-wider">{k}</b><span className="text-[14px] font-semibold">{v}</span></div>)}</div><Barcode value={f.tracking} className="mt-auto h-[48px] w-full"/><div className="text-center font-mono text-[10px]">{f.tracking}</div></div>}
function StandardBarcode({d}:{d:LabelData}){const f=fields(d);return <div className="flex h-full flex-col border-[3px] border-black p-4"><div className="flex justify-between border-b-[3px] border-black pb-2"><span className="text-[22px] font-black">{d.heading.showHeading?d.heading.customHeading||"SHIPPING LABEL":"SHIPPING LABEL"}</span><span className="text-right text-[11px] font-bold">{d.shipping.carrier}<br/>{d.format.serviceLevel}</span></div><div className="grid grid-cols-2 gap-4 border-b-2 border-black py-3"><div><b className="text-[10px]">FROM</b><Address a={d.sender}/></div><div><b className="text-[10px]">SHIP TO</b><Address a={d.recipient}/></div></div><div className="grid grid-cols-3 border-b-2 border-black py-3 text-center text-[10px]"><div><b>PACKAGE</b><br/>{d.package.type}</div><div><b>WEIGHT</b><br/>{f.weight}</div><div><b>DIMENSIONS</b><br/>{f.dims}</div></div><div className="py-3 text-[11px]"><b>REF:</b> {f.reference}<br/><b>SHIP DATE:</b> {date(d.format.shipDate)}<br/><b>HANDLING:</b> {d.tracking.handlingInstructions||"—"}</div><Barcode value={f.tracking} className="mt-auto h-[88px] w-full"/><div className="mt-2 text-center font-mono text-[12px] font-bold">{f.tracking}</div><div className="mt-2 text-center text-[8px]">CUSTOM LABEL · POSTAGE NOT INCLUDED</div></div>}
