import { NextResponse } from "next/server";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { sql } from "@/lib/db";
import { packingSlipSchema, type PackingSlipData } from "@/lib/packing-slip";
import { renderPackingSlipPdf } from "@/lib/packing-slip-pdf";

export const runtime="nodejs";
const safe=(value:string)=>value.replace(/[^a-z0-9-_]+/gi,"-").replace(/^-|-$/g,"").slice(0,60)||"packing-slip";

async function createPdf(data:PackingSlipData,id:string){const pdf=await PDFDocument.create();let page=pdf.addPage([612,792]);const regular=await pdf.embedFont(StandardFonts.Helvetica);const bold=await pdf.embedFont(StandardFonts.HelveticaBold);const ink=rgb(.05,.08,.12),muted=rgb(.35,.4,.45),accent=rgb(.06,.46,.43);let y=744;
  if(data.showLogo&&data.logoDataUrl){try{const bytes=Uint8Array.from(atob(data.logoDataUrl.split(",")[1]),c=>c.charCodeAt(0));const img=data.logoDataUrl.includes("image/png")?await pdf.embedPng(bytes):await pdf.embedJpg(bytes);const scale=Math.min(90/img.width,45/img.height);page.drawImage(img,{x:48,y:720,width:img.width*scale,height:img.height*scale});}catch{}}
  const branded=data.templateCode==="BRANDED"||data.templateCode==="MODERN";if(branded)page.drawRectangle({x:0,y:760,width:612,height:32,color:accent});page.drawText(data.customHeading,{x:data.showLogo&&data.logoDataUrl?165:48,y,size:22,font:bold,color:branded?rgb(1,1,1):ink});page.drawText(`Order ${data.orderNumber}`,{x:420,y,size:10,font:bold,color:branded?rgb(1,1,1):ink});y-=38;
  page.drawText(`Order date: ${data.orderDate}`,{x:48,y,size:9,font:regular,color:muted});if(data.slipNumber)page.drawText(`Slip: ${data.slipNumber}`,{x:420,y,size:9,font:regular,color:muted});y-=28;page.drawLine({start:{x:48,y},end:{x:564,y},thickness:1,color:ink});y-=18;
  const addr=(title:string,a:PackingSlipData["sender"],x:number)=>{page.drawText(title,{x,y,size:8,font:bold,color:accent});page.drawText(a.name,{x,y:y-16,size:11,font:bold,color:ink});let yy=y-30;[a.company,a.addressLine1,a.addressLine2,`${a.city}, ${a.state} ${a.zipCode}`,a.country,a.phone].filter(Boolean).forEach(line=>{page.drawText(line.slice(0,48),{x,y:yy,size:8,font:regular,color:ink});yy-=11;});};addr("FROM",data.sender,48);addr("SHIP TO",data.recipient,330);y-=105;
  const columns=[...(data.showSku?[{key:"sku",label:"SKU",x:48,w:85}]:[]),{key:"description",label:"DESCRIPTION",x:data.showSku?133:48,w:data.showSku?250:335},...(data.showVariant?[{key:"variant",label:"VARIANT",x:383,w:110}]:[]),...(data.showQuantity?[{key:"quantity",label:"QTY",x:520,w:40}]:[])];page.drawRectangle({x:48,y:y-4,width:516,height:22,color:data.templateCode==="MINIMAL"?rgb(.94,.95,.96):accent});columns.forEach(c=>page.drawText(c.label,{x:c.x,y:y+3,size:7,font:bold,color:data.templateCode==="MINIMAL"?ink:rgb(1,1,1)}));y-=24;
  for(const item of data.items){if(y<110){page=pdf.addPage([612,792]);y=744;}columns.forEach(c=>page.drawText(String(item[c.key as keyof typeof item]??"").slice(0,45),{x:c.x,y,size:data.templateCode==="COMPACT"?7:8,font:c.key==="description"?bold:regular,color:ink}));y-=data.templateCode==="COMPACT"?15:21;page.drawLine({start:{x:48,y:y+6},end:{x:564,y:y+6},thickness:.4,color:rgb(.82,.84,.86)});}
  y-=12;if(data.specialInstructions){page.drawText("SPECIAL INSTRUCTIONS",{x:48,y,size:8,font:bold,color:accent});y-=14;page.drawText(data.specialInstructions.slice(0,90),{x:48,y,size:8,font:regular,color:ink});y-=22;}if(data.customerMessage){page.drawText(data.customerMessage.slice(0,100),{x:48,y,size:10,font:bold,color:ink});}page.drawText(data.footerText.slice(0,110),{x:48,y:40,size:7,font:regular,color:muted});page.drawText(`#${id}`,{x:530,y:40,size:7,font:regular,color:muted});return Buffer.from(await pdf.save()).toString("base64");}

export async function POST(request:Request){try{const parsed=packingSlipSchema.safeParse(await request.json());if(!parsed.success)return NextResponse.json({message:"Please correct the highlighted fields.",errors:parsed.error.flatten()},{status:400});const d=parsed.data;const itemsJson=JSON.stringify(d.items.map((item,index)=>({...item,line_number:index+1})));const [created]=await sql`
    WITH fa AS (INSERT INTO addresses(full_name,company_name,address_line_1,address_line_2,city,state,postal_code,country_code,phone) VALUES(${d.sender.name},${d.sender.company||null},${d.sender.addressLine1},${d.sender.addressLine2||null},${d.sender.city},${d.sender.state},${d.sender.zipCode},${d.sender.country},${d.sender.phone||null}) RETURNING id),
    ta AS (INSERT INTO addresses(full_name,company_name,address_line_1,address_line_2,city,state,postal_code,country_code,phone) VALUES(${d.recipient.name},${d.recipient.company||null},${d.recipient.addressLine1},${d.recipient.addressLine2||null},${d.recipient.city},${d.recipient.state},${d.recipient.zipCode},${d.recipient.country},${d.recipient.phone||null}) RETURNING id),
    ps AS (INSERT INTO packing_slips(order_number,order_date,from_address_id,to_address_id,show_sku,show_variant,show_quantity,logo_url,custom_heading,special_instructions,customer_message,footer_text) SELECT ${d.orderNumber},${d.orderDate},fa.id,ta.id,${d.showSku},${d.showVariant},${d.showQuantity},${null},${d.customHeading},${d.specialInstructions||null},${d.customerMessage||null},${d.footerText||null} FROM fa,ta RETURNING id),
    inserted_items AS (INSERT INTO packing_slip_items(packing_slip_id,line_number,sku,description,variant,quantity) SELECT ps.id,i.line_number,i.sku,NULLIF(i.description,''),NULLIF(i.variant,''),i.quantity FROM ps,jsonb_to_recordset(${itemsJson}::jsonb) AS i(line_number int,sku text,description text,variant text,quantity int) RETURNING id)
    SELECT ps.id,(SELECT count(*) FROM inserted_items) AS item_count FROM ps`;
  const id=String(created.id);return NextResponse.json({ok:true,id,itemCount:Number(created.item_count),pdfBase64:await renderPackingSlipPdf(d,id),filename:`packing-slip-${safe(d.orderNumber)}.pdf`},{status:201});}catch(error){console.error("Packing slip generation failed",error);return NextResponse.json({message:"Packing slip generation failed."},{status:500});}}
